### ISSUE TITLE
Pricing Assistant Always recommends custom quote if document size is >1KB

### ISSUE THREAD

**Issue by davelarkan** [meilisearch/landing#417]
**Description**
I believe the logic used to determine a "custom quote" in the pricing assistant is a little too aggressive.
Currently we always recommend a custom quote if the document size is greater than 1KB as you can see here:
 https://github.com/meilisearch/landing/blob/a6f8f390156e19ecec044ab8eff25844e538cf7b/src/utils/getPricingAssistantSuggestion.js#L53  

I believe this is problematic and I'll try to explain why using an example from a real customer I spoke to.

The customer has a fixed dataset that only updates once per year so reindexing happens extremely infrequently. Here are the rest of their requirements with exact numbers:
**_Use case:_** SaaS application
**_Features required:_** [Textual search, Geo search]
**_Number of documents:_** 172,000
**_Size of document:_** ~1.2KB
**_Update frequency:_** Annually

As you can see, the document size is only slightly over 1Kb. If you fill out the pricing assistant and select a document size of _0.5KB-1KB_ we recommend them the $29/month 1GB RAM plan. 

However, because their document size is a few hundred bytes larger at 1.2KB they select a document size of _1KB-10KB_. And as a result we recommend them a Custom quote.

**Expected behavior**
In my example above I would expect the user to be recommended the $122/month 4GB RAM plan.

**Current behavior**
A Custom quote is suggested

**Screenshots or Logs**
N/A
**Environment (please complete the following information):**
N/A

**Comment by mdubus** [comment]
Thanks a lot for your feedback @davelarkan 🙏 

We agreed to remove this line in the conditions, so this should be better now 😀
