### ISSUE TITLE
SEO improvement

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/landing#427]
Hi, I think we can remove or have a way to ignore the information about how many movies we have in the movies index to test Meilisearch :)

below you can see right after the description, we have a value 15880.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/4116980/183316150-dc962e22-2a58-4719-846c-fe8db234699f.png">

**Comment by mdubus** [comment]
Hello @brunoocasali 👋

Thanks a lot for your issue. Unfortunately, I cannot change this as Google decides what appear in its search result. 
As you can see in the landing source code (`view-source:https://www.meilisearch.com/`):

<img width="1115" alt="Capture d’écran 2022-08-08 à 09 34 10" src="https://user-images.githubusercontent.com/30866152/183364735-f5f7e5db-88d4-424d-b16f-c6da610cbff0.png">

we already provide a meta description we would like to be displayed, but Google can decide to use it, or ignore it and put what he thinks is more appropriate. 
In our case, he decides to use the text from the `Interactive Search` block + the number of movies on the left: 
<img width="1261" alt="Capture d’écran 2022-08-08 à 09 37 06" src="https://user-images.githubusercontent.com/30866152/183364934-64e52c33-5c62-41df-bbff-f05cecaa7a1a.png">

We cannot do much about it but hope that Google will update it by himself 🤷‍♀️ I will therefore close this issue, but don't hesitate to open other issues if you find anything that doesn't seems fine to you 😀
