### ISSUE TITLE
Add default values to Instant Meilisearch's client

### ISSUE THREAD

**Issue by mdubus** [meilisearch/landing#461]
**Description**
The Interactive Search component [on the homepage](https://www.meilisearch.com/) allows us to display and search inside movies: 

<img width="532" alt="Capture d’écran 2022-09-13 à 09 13 57" src="https://user-images.githubusercontent.com/30866152/189835078-259bc30d-0f88-4376-9b92-b5dd8f243f8f.png">

To do so, we use [Instant Meilisearch](https://github.com/meilisearch/instant-meilisearch). The client needs to be initialized with a host and an apiKey (`NEXT_PUBLIC_DEMO_MOVIES_HOST` and `NEXT_PUBLIC_DEMO_MOVIES_API_KEY`).

By running the website locally, these environment variables are loaded thanks to a `.env` file, but if they are not provided, the website crashes on `yarn dev`:

<img width="1014" alt="Capture d’écran 2022-09-13 à 09 17 33" src="https://user-images.githubusercontent.com/30866152/189835774-102bdd71-09d6-4bcc-b262-7e34c36357c6.png">

We should provide a default value to these environment variables. I suggest `http://0.0.0.0:7700` as a host, and `searchKey` for the apiKey.

The changes should be made inside the `src/components/InteractiveSearch.js` component, inside the `.env.example`, and also inside the `src/stories/Searchbox.stories.js` file as well.

**Comment by arifszn** [comment]
@mdubus I have created a PR for this. Can you please authorize it?

**Comment by bidoubiwa** [comment]
Hey @arifszn, @mdubus is away at the moment :) Thanks for your contribution! I will review it

**Comment by mdubus** [comment]
Fixed by #486
