### ISSUE TITLE
Develop the `About us` page

### ISSUE THREAD

**Issue by mdubus** [meilisearch/landing#476]
There are the blocks that we will need for this new page:

- [ ] Hero #477
- [ ] Team members #478
- [ ] History #479
- [ ] Values #480
- [ ] Investors #481
- [ ] Benefits #482
- [ ] Opened positions / CTA to join us #483

**Comment by nooras** [comment]
HI @mdubus Can I work on it? if yes! is there any UI design for about us page?

**Comment by mdubus** [comment]
Hello @nooras  👋 

Thanks a lot for your interest. This issue isn't opened for hacktoberfest contributions, as our UI is in private. 

Have a nice day! ✨🦕
