### ISSUE TITLE
Add proper aria to improve lighthouse score

### ISSUE THREAD

**Issue by developer-diganta** [meilisearch/landing#487]
**Description**
Buttons and links (some) do not have aria and hence are affecting the lighthouse score. 

**Expected behavior**
NA

**Current behavior**
NA

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/65999534/193426777-bbdfa7e7-733a-4eb9-aa73-8705ceb97522.png)

**Environment (please complete the following information):**

- Browser: Chrome(106)

**Comment by developer-diganta** [comment]
If the issue seems important, can I work on it?

**Comment by bidoubiwa** [comment]
Hey @developer-diganta! Yes this seems to be a great addition. You can work on it, thanks so much :)

**Comment by bidoubiwa** [comment]
Yes, this is linked to that issue: https://github.com/meilisearch/landing/issues/461

To run the tests you need to have a running Meilisearch and add the credentials in a `.env` file. 

The contributing guide should be more clear about this. I'll open an issue! Thanks for this feedback :)

**Comment by bidoubiwa** [comment]
Issue : #499

**Comment by mdubus** [comment]
Fixed with #500
