### ISSUE TITLE
Remove `npm` mentions in Contributing guide.

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/landing#496]
In the contributing guide we are suggesting to either start the project with `npm` or `yarn`. 
Since we are using a `yarn.lock`, by using `npm` we are not using the fixed packages versions with which we know the project runs in the expected way. 

Thus, `npm` should not be suggested. Only yarn.

**Comment by joanjeremiah** [comment]
I would like to solve this issue. Kindly assign this to me.

**Comment by CaroFG** [comment]
Hi @joanjeremiah, thank you for your interest in contributing to Meilisearch! As stated in the [CONTRIBUTING](https://github.com/meilisearch/landing/blob/main/CONTRIBUTING.md) guidelines:

> There will be no issue assignment as we don’t want people to ask to be assigned specific issues and never return, discouraging the volunteer contributors from opening a PR to fix this issue. We take the liberty to choose the PR that best fixes the issue, so we encourage you to get to it as soon as possible and do your best!

**Comment by joanjeremiah** [comment]
I made the pull request. Kindly look into it.
