### ISSUE TITLE
Add `percy` inside `bors.toml` file

### ISSUE THREAD

**Issue by mdubus** [meilisearch/landing#505]
Currently, `bors` only checks the statuses of the `linter_check` and `cypress-run` tests.
We want to add also the `percy` test, as it is a requirement before merging a PR.

**Comment by developer-diganta** [comment]
Would love to work on it. If I am right, I'll simply need to add percy to bors.toml? Or is any other configuration required?

**Comment by mdubus** [comment]
Yes, you just have to do this, no trap here! 😄
