### ISSUE TITLE
Transform `getPricingPageData` function into `pricingPageData` object

### ISSUE THREAD

**Issue by mdubus** [meilisearch/landing#551]
We currently have every text of the website inside the `data` folder, separated in different files.

The one for the homepage is the `data/pricing.js`. It exports a function called `getPricingPageData` which doesn't receive any argument. This is legacy code, and we would like to rework it in order to have an object instead. 

What we have to do is: 
- Transform the `getPricingPageData`  function of the `data/pricing.js` file into an object
- Rename `getPricingPageData` into `pricingPageData` in every file that uses it (including the `stories` folder used by Storybook)

**Comment by simonpankovski** [comment]
Hey, can I work on this issue?

**Comment by mdubus** [comment]
Hello @simonpankovski 👋

Sure go ahead!
Just note that we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages volunteer contributors to open a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](https://github.com/meilisearch/landing/blob/main/CONTRIBUTING.md).

We are looking forward to reviewing your PR!

**Comment by simonpankovski** [comment]
No problem, I understand. I'll start working on it shortly and submit my PR when I'm done. Thanks for letting me know :)

**Comment by johnhorsema** [comment]
@simonpankovski sorry I was about to push when you posted your reply
@mdubus Opened a PR here #553

**Comment by simonpankovski** [comment]
@johnhorsema Ah, okay then go ahead. I'll look out for other issues in the future.
