### ISSUE TITLE
Hamburger menu is broken on Safari mobiles

### ISSUE THREAD

**Issue by mdubus** [meilisearch/landing#556]
**Description**
The hamburger menu doesn't display well, it's cropped.

**Expected behavior**
It should display entirely

**Screenshots or Logs**

https://user-images.githubusercontent.com/30866152/197973606-46476b7c-a7eb-48cb-a03d-0b742310e9e7.mov

**Environment (please complete the following information):**

- Browser: Version 15.6.1 (17613.3.9.1.16)
- Viewport: mobile devices (ex: 400px wide)

**Comment by vasucp1207** [comment]
@mdubus, I want to work on this issue can you assign this to me.
